const fs=require("fs"),R=process.env.VX_ROOT||"/app/",d=R+"apps/chat/.output/";
function P(f,a,b,mark){let s=fs.readFileSync(f,"utf8");if(mark&&s.includes(mark))return;let n=s.replace(a,b);fs.writeFileSync(f,n)}
P(d+"public/assets/routes-Vy1004Fb.js",/src:`about:blank`,ref:\(f\)=>\{.*?\},title:/,"src:`/api/public/embed/`,title:","src:`/api/public/embed/`");
P(d+"server/_ssr/routes-C8-LyYk7.mjs",'src: "about:blank"','src: "/api/public/embed/"','src: "/api/public/embed/"');
const r=d+"server/_ssr/router-C37aqUq5.mjs",U='headers.set("user-agent", request.headers.get("user-agent") ?? "Mozilla/5.0");';
P(r,U+"\n\tconst upstream",U+'\n\tconst ip=request.headers.get("x-forwarded-for")||request.headers.get("x-real-ip");if(ip){headers.set("x-forwarded-for",ip);headers.set("x-real-ip",ip);}\n\tconst upstream',"const ip=");
P(r,/\n\telse if \(contentType\.includes\("javascript"\) \|\| contentType\.includes\("application\/json"\)\) rewritten = rewritten\.replace[^\n]*/,"","");
P(r,'var PROXY_PREFIX = "/api/public/embed";\n','var PROXY_PREFIX = "/api/public/embed";\n'+"\nvar __VXS = \"(function(){if(window.__vxfx)return;var R=/^(https?|wss?):\\\\/\\\\/((?:[a-z0-9-]+\\\\.)*(?:gstatic\\\\.com|googleapis\\\\.com|firebasedatabase\\\\.app|firebaseio\\\\.com|firebasestorage\\\\.app|jsdelivr\\\\.net|unpkg\\\\.com))(?=[\\\\/?#]|$)/i;function fx(u){try{var s=String(u&&u.href?u.href:u);var m=s.match(R);if(!m)return u;var w=m[1].charAt(0).toLowerCase()===\\\"w\\\";return(w?(location.protocol===\\\"https:\\\"?\\\"wss://\\\":\\\"ws://\\\"):location.protocol+\\\"//\\\")+location.host+\\\"/__x/\\\"+m[2].toLowerCase()+s.slice(m[0].length)}catch(e){return u}}window.__vxfx=fx;var F=window.fetch;if(F)window.fetch=function(i,o){try{if(typeof i===\\\"string\\\"||(i&&i.href&&!i.url))i=fx(i);else if(i&&i.url){var n=fx(i.url);if(n!==i.url)i=new Request(n,i)}}catch(e){}return F.call(this,i,o)};var X=XMLHttpRequest.prototype.open;XMLHttpRequest.prototype.open=function(){arguments[1]=fx(arguments[1]);return X.apply(this,arguments)};var W=window.WebSocket;if(W){var NW=function(u,p){return p===undefined?new W(fx(u)):new W(fx(u),p)};NW.prototype=W.prototype;NW.CONNECTING=0;NW.OPEN=1;NW.CLOSING=2;NW.CLOSED=3;window.WebSocket=NW}var E=window.EventSource;if(E){var NE=function(u,o){return new E(fx(u),o)};NE.prototype=E.prototype;window.EventSource=NE}if(navigator.sendBeacon){var B=navigator.sendBeacon.bind(navigator);navigator.sendBeacon=function(u,d){return B(fx(u),d)}}[[window.HTMLImageElement,\\\"src\\\"],[window.HTMLScriptElement,\\\"src\\\"],[window.HTMLLinkElement,\\\"href\\\"],[window.HTMLSourceElement,\\\"src\\\"],[window.HTMLMediaElement,\\\"src\\\"]].forEach(function(a){try{var P=a[0].prototype,d=Object.getOwnPropertyDescriptor(P,a[1]);if(!d||!d.set)return;Object.defineProperty(P,a[1],{configurable:true,enumerable:d.enumerable,get:d.get,set:function(v){return d.set.call(this,fx(v))}})}catch(e){}});var SA=Element.prototype.setAttribute;Element.prototype.setAttribute=function(n,v){if(n===\\\"src\\\"||n===\\\"href\\\")v=fx(v);return SA.call(this,n,v)};})();\";\nvar __VXT = /https?:\\/\\/((?:[a-z0-9-]+\\.)*(?:gstatic\\.com|googleapis\\.com|firebasedatabase\\.app|firebaseio\\.com|firebasestorage\\.app|jsdelivr\\.net|unpkg\\.com))(?=[\\/\"'`\\s?#)\\\\;,]|$)/gi;\nfunction __vx(t, ct, request) {\n\tconst h = String(request.headers.get(\"x-forwarded-host\") || new URL(request.url).host).split(\",\")[0].trim();\n\tconst p = String(request.headers.get(\"x-forwarded-proto\") || \"https\").split(\",\")[0].trim();\n\tconst b = p + \"://\" + h;\n\tt = t.replace(__VXT, (m, x) => b + \"/__x/\" + x.toLowerCase());\n\tt = t.replace(/(databaseURL\\s*:\\s*[\"'`])https?:\\/\\/[^\"'`\\/]+\\/__x\\/([^\\/\"'`]+)/g, \"$1https://$2\");\n\tif (ct.includes(\"text/html\")) t = t.replace(/(<head(?:\\s[^>]*)?>)/i, (m) => m + \"<script>\" + __VXS + \"</script>\");\n\treturn t;\n}\n","__VXS");
P(r,"return new Response(rewriteText(body, contentType), {","return new Response(__vx(rewriteText(body, contentType), contentType, request), {","__vx(rewriteText");
const g=R+"gateway.js",A="  if (appKey) {\n    req.__vysloApp = appKey;\n    return proxy.web(req, res, targetFor(appKey));\n  }\n\n  res.writeHead(302";
P(g,"const server = http.createServer(","const EXT_RE=/^(?:[a-z0-9-]+\\.)*(?:gstatic\\.com|googleapis\\.com|firebasedatabase\\.app|firebaseio\\.com|firebasestorage\\.app|jsdelivr\\.net|unpkg\\.com)$/i;\nconst EXT_TXT=/https?:\\/\\/((?:[a-z0-9-]+\\.)*(?:gstatic\\.com|googleapis\\.com|firebasedatabase\\.app|firebaseio\\.com|firebasestorage\\.app|jsdelivr\\.net|unpkg\\.com))(?=[\\/\"'`\\s?#)\\\\;,]|$)/gi;\nconst EXT_UP=\"https://vyslo-mix-chat10041958.edgeone.dev\";\nfunction extBase(req){const h=String(req.headers[\"x-forwarded-host\"]||req.headers.host||\"\").split(\",\")[0].trim();let p=String(req.headers[\"x-forwarded-proto\"]||\"\").split(\",\")[0].trim();if(!p)p=/^(localhost|127\\.)/.test(h)?\"http\":\"https\";return p+\"://\"+h}\nfunction extRw(t,b){return t.replace(EXT_TXT,(m,h)=>b+\"/__x/\"+h.toLowerCase())}\nasync function handleExt(req,res){const m=req.url.match(/^\\/__x\\/([^\\/?#]+)(.*)$/);if(!m||!EXT_RE.test(m[1])){res.writeHead(403);return res.end()}\nconst base=extBase(req),url=\"https://\"+m[1].toLowerCase()+(m[2]&&m[2][0]!==\"/\"?\"/\"+m[2]:(m[2]||\"/\"));const h={};\nfor(const k of Object.keys(req.headers)){if(/^(if-none-match|if-modified-since|host|cookie|connection|upgrade|origin|referer|accept-encoding|content-length|transfer-encoding|keep-alive|te|trailer|proxy-.*|sec-fetch-.*|x-forwarded-(host|proto|port)|x-railway-.*)$/i.test(k))continue;h[k]=req.headers[k]}\nh.origin=EXT_UP;h.referer=EXT_UP+\"/\";let body;if(req.method!==\"GET\"&&req.method!==\"HEAD\"){const c=[];for await(const x of req)c.push(x);body=Buffer.concat(c)}\nconst r=await fetch(url,{method:req.method,headers:h,body,redirect:\"manual\"});const o={};\nr.headers.forEach((v,k)=>{if(/^(content-security-policy.*|x-frame-options|content-encoding|content-length|set-cookie|etag|last-modified|transfer-encoding|connection|access-control-.*|strict-transport-security|alt-svc|cross-origin-.*)$/i.test(k))return;o[k]=v});\nif(o.location)o.location=extRw(o.location,base);const ct=r.headers.get(\"content-type\")||\"\";\nif(req.method!==\"HEAD\"&&r.body&&/javascript|text\\/css|text\\/html|json/i.test(ct)){const t=extRw(await r.text(),base);o[\"cache-control\"]=\"no-store, max-age=0\";o[\"content-length\"]=Buffer.byteLength(t);res.writeHead(r.status,o);return res.end(t)}\nres.writeHead(r.status,o);if(!r.body||req.method===\"HEAD\")return res.end();require(\"stream\").Readable.fromWeb(r.body).on(\"error\",()=>res.destroy()).pipe(res)}\n"+"\nconst server = http.createServer(","function handleExt");
P(g,'  if (pathname.startsWith("/__idsync/")) {','  if (pathname.startsWith("/__x/")) { handleExt(req, res).catch((e) => { console.error("[ext]", e.message, req.url); if (!res.headersSent) res.writeHead(502); res.end(); }); return; }\n  if (pathname.startsWith("/__idsync/")) {','startsWith("/__x/")');
P(g,'server.on("upgrade", (req, socket, head) => {\n','server.on("upgrade", (req, socket, head) => {\n  { const m = req.url.match(/^\\/__x\\/([^\\/?#]+)(.*)$/); if (m) { if (!EXT_RE.test(m[1])) return socket.destroy(); req.url = m[2] || "/"; req.headers.origin = EXT_UP; return proxy.ws(req, socket, head, { target: "https://" + m[1].toLowerCase(), changeOrigin: true }); } }\n',"if (!EXT_RE.test(m[1])) return socket.destroy()");
P(g,"  // ヘルスチェック (Railway)\n","  // チャット: サーバー経由で埋め込み元を表示 (URL 直下で配信)\n  {\n    const dest = req.headers[\"sec-fetch-dest\"];\n    const isEmbed = /^\\/api\\/public\\/embed(\\/|$)/.test(pathname);\n    const isRoot = pathname === \"/\" || pathname === \"/index.html\";\n    let chat = isEmbed;\n    if (!chat && currentApp(req) === \"chat\" && !/^\\/(__x|__idsync|portal|version)(\\/|$)/.test(pathname) && !TAB_ICONS[pathname] && !APPS[pathname.split(\"/\")[1]]) {\n      chat = isRoot ? (dest === \"iframe\" || (!dest && !/[?&]app=/.test(req.url))) : dest !== \"document\";\n    }\n    if (chat) {\n      if (!isEmbed && /^\\/(service-worker|firebase-messaging-sw)\\.js$/.test(pathname)) { res.writeHead(404, { \"Cache-Control\": \"no-store\" }); return res.end(); }\n      if (!isEmbed) req.url = \"/api/public/embed\" + req.url;\n      req.__vysloApp = \"chat\";\n      return proxy.web(req, res, targetFor(\"chat\"));\n    }\n  }\n"+"  // ヘルスチェック (Railway)\n","チャット: サーバー経由で埋め込み元を表示");
P(r,'\t\t"range",\n\t\t"if-none-match",\n\t\t"if-modified-since"\n','\t\t"range"\n',"__norevalidate_never");
P(r,'\t\t"set-cookie"\n\t]) responseHeaders.delete(name);\n\tresponseHeaders.set("cache-control", "no-cache");','\t\t"set-cookie",\n\t\t"etag",\n\t\t"last-modified"\n\t]) responseHeaders.delete(name);\n\tresponseHeaders.set("cache-control", "no-store, max-age=0");',"no-store, max-age=0");
P(r,'var PROXY_PREFIX = "/api/public/embed";','var PROXY_PREFIX = "";','var PROXY_PREFIX = "";');
